#!/usr/bin/env python3
"""
Build script for deploying Partner Center to Hostinger FTP.
1. Runs npm build (outputs to dist-frontend/)
2. Copies frontend build and backend PHP to dist/
3. Excludes sensitive files (.env, secrets.php)
"""

import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "dist"
FRONTEND_BUILD = ROOT / "dist-frontend"


BACKEND_FILES = [
    "api.php",
    "auth.php",
    "config.php",
    "GoogleAuthenticator.php",
    "login.php",
    "ratelimit.php",
    "setup.php",
    "supabase.php",
    "upload.php",
    "validation.php",
    "whitelist.php",
]

EXCLUDE_BACKEND = {
    "secrets.php",
}


def run_npm_build() -> bool:
    """Run npm build command."""
    print("Running npm build...")
    try:
        result = subprocess.run(
            ["npm", "run", "build"],
            cwd=ROOT,
            shell=True,  # Required for Windows
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            print(f"npm build failed:\n{result.stderr}")
            return False
        print("npm build completed successfully.")
        return True
    except FileNotFoundError:
        print("npm not found. Please ensure Node.js is installed.")
        return False


def copy_frontend() -> None:
    """Copy Vite build output to dist."""
    if not FRONTEND_BUILD.exists():
        print(f"Frontend build not found at {FRONTEND_BUILD}")
        return
    
    # Copy all files from dist-frontend to dist
    for item in FRONTEND_BUILD.iterdir():
        dst = DIST / item.name
        if item.is_dir():
            if dst.exists():
                shutil.rmtree(dst)
            shutil.copytree(item, dst)
        else:
            shutil.copy2(item, dst)
    
    print(f"Copied frontend build from {FRONTEND_BUILD}")


def copy_backend() -> None:
    """Copy backend PHP files to dist/backend."""
    backend_src = ROOT / "backend"
    backend_dst = DIST / "backend"
    backend_dst.mkdir(parents=True, exist_ok=True)
    
    for filename in BACKEND_FILES:
        src = backend_src / filename
        if src.exists():
            shutil.copy2(src, backend_dst / filename)
    
    # Copy .htaccess if exists
    htaccess = backend_src / ".htaccess"
    if htaccess.exists():
        shutil.copy2(htaccess, backend_dst / ".htaccess")
    
    print(f"Copied backend files to {backend_dst}")


def copy_root_files() -> None:
    """Copy root-level files needed for deployment."""
    root_files = [
        ".htaccess",
        "index.php",
        "README.md",
    ]
    
    for filename in root_files:
        src = ROOT / filename
        if src.exists():
            shutil.copy2(src, DIST / filename)
    
    # Copy public folder contents
    public_src = ROOT / "public"
    if public_src.exists():
        for item in public_src.iterdir():
            shutil.copy2(item, DIST / item.name)
    
    print("Copied root files and public assets")


def create_app_html() -> None:
    """
    Create app.html that loads the Vite-built assets.
    This is loaded by index.php after authentication.
    """
    # Read the index.html generated by Vite
    index_html = DIST / "index.html"
    app_html = DIST / "app.html"
    
    if index_html.exists():
        # Just copy index.html as app.html (they're the same content)
        shutil.copy2(index_html, app_html)
        print("Created app.html from Vite index.html")


def main() -> None:
    # Clean dist folder
    if DIST.exists():
        shutil.rmtree(DIST)
    DIST.mkdir(parents=True, exist_ok=True)
    print(f"Cleaned dist folder: {DIST}")
    
    # Run npm build
    if not run_npm_build():
        print("Build failed. Exiting.")
        sys.exit(1)
    
    # Copy frontend build
    copy_frontend()
    
    # Copy backend
    copy_backend()
    
    # Copy root files
    copy_root_files()
    
    # Create app.html
    create_app_html()
    
    # Final cleanup - ensure secrets are never included
    secrets_path = DIST / "backend" / "secrets.php"
    if secrets_path.exists():
        secrets_path.unlink()
    
    env_path = DIST / ".env"
    if env_path.exists():
        env_path.unlink()
    
    print(f"\n[OK] Build complete! Deploy contents of: {DIST}")
    print("\nDist contents:")
    for item in sorted(DIST.rglob("*")):
        if item.is_file():
            rel = item.relative_to(DIST)
            print(f"  {rel}")


if __name__ == "__main__":
    main()
