<?php
require 'auth.php';
require 'ratelimit.php';

// Setup is complete when .env exists at project root and secrets.php exists in backend
$envPath = __DIR__ . '/../.env';
$secretsPath = __DIR__ . '/secrets.php';
if (file_exists($envPath) && file_exists($secretsPath)) {
    die("Setup already completed. Delete .env and backend/secrets.php to restart.");
}

$step = $_GET['step'] ?? 1;
$error = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    enforceSameOriginPost();

    // Rate limit setup flow (per IP)
    $ip = getClientIpAddress();
    if (!rateLimit("setup:ip:$ip", 30, 15 * 60)) {
        http_response_code(429);
        die("Too many requests. Try again later.");
    }

    if ($step == 1) {
        // Database Config
        $url = rtrim($_POST['supabase_url'], '/');
        $key = $_POST['supabase_key'];
        
        // Test connection
        $ch = curl_init($url . '/rest/v1/'); // health check or root
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, [
            "apikey: $key",
            "Authorization: Bearer $key"
        ]);
        $res = curl_exec($ch);
        $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);
        
        if ($code >= 200 && $code < 500) {
            $_SESSION['setup_db'] = ['url' => $url, 'key' => $key];
            header("Location: setup.php?step=2");
            exit;
        } else {
            $error = "Failed to connect to Supabase. Check URL/Key.";
        }
    } elseif ($step == 2) {
        // Security Config
        $pass = $_POST['password'];
        $confirm = $_POST['confirm'];
        
        if ($pass !== $confirm) {
            $error = "Passwords do not match.";
        } elseif (strlen($pass) < 8) {
            $error = "Password too short (min 8 chars).";
        } else {
            $_SESSION['setup_pass'] = password_hash($pass, PASSWORD_DEFAULT);
            header("Location: setup.php?step=3");
            exit;
        }
    } elseif ($step == 3) {
        // 2FA & Finalize
        require_once 'GoogleAuthenticator.php';
        $ga = new PHPGangsta_GoogleAuthenticator();
        $secret = $_POST['secret'];
        $code = $_POST['code'];
        
        if ($ga->verifyCode($secret, $code, 2)) {
            // Save everything
            $db = $_SESSION['setup_db'];
            $passHash = $_SESSION['setup_pass'];
            
            // Write .env at project root (blocked by .htaccess)
            $envContent = "# Generated by backend/setup.php\n"
                . "APP_ENV=production\n"
                . "SUPABASE_URL=" . $db['url'] . "\n"
                . "SUPABASE_SERVICE_ROLE_KEY=" . $db['key'] . "\n";
            file_put_contents($envPath, $envContent);
            
            // Write secrets.php
            $secretsContent = "<?php\nreturn " . var_export(['master_hash' => $passHash, '2fa_secret' => $secret], true) . ";\n";
            file_put_contents('secrets.php', $secretsContent);
            
            // Redirect to login
            header("Location: /backend/login.php");
            exit;
        } else {
            $error = "Invalid 2FA Code.";
        }
    }
}

// Prepare Step 3 QR
$qrUrl = '';
$newSecret = '';
if ($step == 3) {
    require_once 'GoogleAuthenticator.php';
    $ga = new PHPGangsta_GoogleAuthenticator();
    $newSecret = $ga->createSecret();
    $qrUrl = $ga->getQRCodeGoogleUrl('PartnerCenter', $newSecret);
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>System Setup - Step <?= $step ?>/3</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-900 text-white flex items-center justify-center min-h-screen">
    <div class="bg-slate-800 p-8 rounded-xl shadow-lg border border-slate-700 w-full max-w-md">
        <div class="mb-6 text-center">
            <h1 class="text-2xl font-bold">Initial Setup</h1>
            <div class="flex justify-center gap-2 mt-2">
                <div class="h-2 w-8 rounded-full <?= $step >= 1 ? 'bg-blue-500' : 'bg-slate-700' ?>"></div>
                <div class="h-2 w-8 rounded-full <?= $step >= 2 ? 'bg-blue-500' : 'bg-slate-700' ?>"></div>
                <div class="h-2 w-8 rounded-full <?= $step >= 3 ? 'bg-blue-500' : 'bg-slate-700' ?>"></div>
            </div>
        </div>

        <?php if ($error): ?>
            <div class="bg-red-500/20 text-red-300 p-3 rounded mb-4 text-sm text-center"><?= $error ?></div>
        <?php endif; ?>

        <form method="POST">
            <?php if ($step == 1): ?>
                <h2 class="text-lg font-medium mb-4">1. Database Connection</h2>
                <div class="space-y-4">
                    <div>
                        <label class="block text-sm mb-1 text-slate-400">Supabase URL</label>
                        <input name="supabase_url" required class="w-full bg-slate-900 border border-slate-600 rounded px-3 py-2 focus:ring-2 focus:ring-blue-500" placeholder="https://xyz.supabase.co">
                    </div>
                    <div>
                        <label class="block text-sm mb-1 text-slate-400">Service Role Key</label>
                        <input name="supabase_key" required class="w-full bg-slate-900 border border-slate-600 rounded px-3 py-2 focus:ring-2 focus:ring-blue-500" placeholder="eyJh...">
                    </div>
                    <button class="w-full bg-blue-600 hover:bg-blue-500 py-2 rounded font-bold">Test & Next</button>
                </div>
            <?php elseif ($step == 2): ?>
                <h2 class="text-lg font-medium mb-4">2. Master Password</h2>
                <div class="space-y-4">
                    <div>
                        <label class="block text-sm mb-1 text-slate-400">Create Password</label>
                        <input type="password" name="password" required class="w-full bg-slate-900 border border-slate-600 rounded px-3 py-2 focus:ring-2 focus:ring-blue-500">
                    </div>
                    <div>
                        <label class="block text-sm mb-1 text-slate-400">Confirm Password</label>
                        <input type="password" name="confirm" required class="w-full bg-slate-900 border border-slate-600 rounded px-3 py-2 focus:ring-2 focus:ring-blue-500">
                    </div>
                    <button class="w-full bg-blue-600 hover:bg-blue-500 py-2 rounded font-bold">Next</button>
                </div>
            <?php elseif ($step == 3): ?>
                <h2 class="text-lg font-medium mb-4">3. Two-Factor Auth</h2>
                <div class="space-y-4 text-center">
                    <div class="bg-white p-4 rounded inline-block">
                        <img src="<?= $qrUrl ?>" />
                    </div>
                    <p class="text-xs text-slate-400 font-mono"><?= $newSecret ?></p>
                    <input type="hidden" name="secret" value="<?= $newSecret ?>">
                    
                    <div>
                        <label class="block text-sm mb-1 text-slate-400">Enter Code</label>
                        <input name="code" required class="w-full bg-slate-900 border border-slate-600 rounded px-3 py-2 text-center text-xl tracking-widest focus:ring-2 focus:ring-blue-500" placeholder="000000" autocomplete="off">
                    </div>
                    <button class="w-full bg-green-600 hover:bg-green-500 py-2 rounded font-bold">Finish Setup</button>
                </div>
            <?php endif; ?>
        </form>
    </div>
</body>
</html>

