import argparse
from pathlib import Path


def main() -> None:
    p = argparse.ArgumentParser(description="Create/overwrite .env for PartnerCenter (server-side secrets).")
    p.add_argument("--url", required=True, help="Supabase URL, e.g. https://xxxx.supabase.co")
    p.add_argument("--service-role-key", required=True, help="Supabase service_role key (server-side only)")
    p.add_argument("--env", default="production", help="APP_ENV value (default: production)")
    p.add_argument("--out", default=".env", help="Output file path (default: .env)")
    p.add_argument("--force", action="store_true", help="Overwrite output file if it exists")
    args = p.parse_args()

    out = Path(args.out)
    if out.exists() and not args.force:
        raise SystemExit(f"Refusing to overwrite {out}. Use --force to overwrite.")

    content = (
        "# Generated by scripts/create_env.py\n"
        f"APP_ENV={args.env}\n"
        f"SUPABASE_URL={args.url.strip()}\n"
        f"SUPABASE_SERVICE_ROLE_KEY={args.service_role_key.strip()}\n"
    )

    out.write_text(content, encoding="utf-8")
    print(f"Wrote {out} ({len(content)} bytes)")


if __name__ == "__main__":
    main()


